(display 10)
(display "\n")
(display (+ 5 3 4))
(display "\n")
(display (- 9 1))
(display "\n")
(display (/ 6 2))
(display "\n")
(display (+ (* 2 4) (- 4 6)))
(display "\n")
(define a 3)
(define b (+ a 1))
(display (+ a b (* a b)))
(display "\n")
(display (= a b))
(display "\n")
(display (if (and (> b a) (< b (* a b)))
              b
              a))
(display "\n")
(display (cond ((= a 4) 6)
               ((= b 4) (+ 6 7 a))
               (else 25)))
(display "\n")
(display (+ 2 (if (> b a) b a)))
(display "\n")
(display (* (cond ((> a b) a)
                  ((< a b) b)
                  (else -1))
          (+ a 1)))
(exit)