(define (square x) (* x x))
(define (sum-of-squares x y)
    (+ (square x)
       (square y)))
(define (bigger-sum-of-squares a b c) 
    (cond ((and (> a c) (> b c)) (sum-of-squares a b))
          ((and (> a b) (> c b)) (sum-of-squares a c))
          ((and (> b a) (> c a)) (sum-of-squares b c))
    ))
(display (= (bigger-sum-of-squares 0 2 2) 8))
(display "\n")
(display (= (bigger-sum-of-squares 2 1 3) 13))
(display "\n")
(display (= (bigger-sum-of-squares 7 3 5) 74))
(exit)